### ISSUE TITLE
Can't get past the ssid setup

### ISSUE THREAD

**Issue by jon1012** [chrismelba/lightclockwifiv2#2]
When I select an ssid in the setup page, I get an error loading the password page.
It gets stuck loading the password_html from what it seems.

Here is the error :

WiFi connected
192.168.4.1
Web server started
nightmode 0
Sending webHandleConfig
Sending webHandleConfig
Sending webHandlePassword

Exception (3):
epc1=0x4000bf64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40249951 depc=0x00000000

ctx: cont 
sp: 3fff2a50 end: 3fff2d70 offset: 01a0

stack>>>
3fff2bf0:  3ffe8c93 40002394 3fff1d18 402138e0  
3fff2c00:  40249951 00000064 3fff1d18 4021394c  
3fff2c10:  40001f46 00000001 3fff1d18 402087d2  
3fff2c20:  3fff0032 0000000f 00000000 40212936  
3fff2c30:  3fff4a50 4010696e 00000000 00000000  
3fff2c40:  00000000 3fff0d08 3fff2d10 402128ae  
3fff2c50:  3fff4848 0000000e 3fff2ca0 40212906  
3fff2c60:  00000000 3fff2cd0 3fff2ca0 00000001  
3fff2c70:  00000001 00000001 3fff4610 40211db6  
3fff2c80:  00000000 00000001 3fff4610 4020e16a  
3fff2c90:  4020e174 3fff4610 3fff2cc0 4020e1a8  
3fff2ca0:  3fff4a60 0000000f 0000000e 40212a5c  
3fff2cb0:  4020e174 3fff4610 3fff0d08 4020e3b4  
3fff2cc0:  3fff4848 0000000f 0000000e 4020c000  
3fff2cd0:  3ffe975f 00000002 00000240 3fff6cf8  
3fff2ce0:  3fff60f0 00000240 0000000f 4020ac6d  
3fff2cf0:  00000000 3fff6cd0 3fff0cc8 00000000  
3fff2d00:  3fff0c30 000003e9 3fff0d08 4020e460  
3fff2d10:  3ffe97f8 00000000 000003e8 00008a7c  
3fff2d20:  3fff0c38 3fff6cd0 3fff0be4 4020aae4  
3fff2d30:  3fff0c30 00000000 3fff0be4 40209cb6  
3fff2d40:  40211b41 00000000 00000000 3fff1d44  
3fff2d50:  3fffdc20 00000000 3fff1d3d 40211b69  
3fff2d60:  00000000 00000000 3fff1d50 40100114  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

**Comment by jon1012** [comment]
Forgot to mention : using a nodemcu v1.0 (amica r2)

**Comment by chrismelba** [comment]
A few people are getting this bug. Try clearing the eeprom (there should be
an example sketch) then try again. If this works please let me know as I
can then update my code.

**Comment by simpleex** [comment]
Same here.
I don't see SSID list (only variables &css &ssids). Have to manually enter SSID.
then when connected and accessing Clock interface, I cannot reach http://X.X.X.X/settings when clicking on settings button.
Cleared EEprom, Nothing changes.

**Comment by chrismelba** [comment]
Sounds like it isn't sending the html correctly. Do you have serial plugged
in? What output does it give?

**Comment by simpleex** [comment]
1 - FIRST RUN (EEPROM CLEARED ) :

scan done
15Networks found
1: FlorreBox (-92)*
2: FreeWifi (-90) (OPEN)
3: FreeWifi (-92) (OPEN)
4: FreeWifi_secure (-89) (OPEN)
5: COYOTE (-88)*
6: COYOTE1 (-51)*
7: FreeWifi_secure (-91) (OPEN)
8: SFR WiFi Mobile (-88) (OPEN)
9: NEUF_5FA8 (-91)*
10: SFR WiFi Public (-89) (OPEN)
11: FreeWifi_secure (-94) (OPEN)
12: FreeWifi (-90) (OPEN)
13: Colchester (-92)*
14: FreeWifi_secure (-89) (OPEN)
15: FREEBOX_OUAHIBA_XQ (-86)*

USP Server started
Access point started with name The Light Clock
Access point started with name The Light Clock

WiFi connected
192.168.4.1
Web server started
nightmode 0

//////////////////  I PICK MY SSID AND ENTER PASSWORD ///////

Sending webHandleConfig
Sending webHandlePassword
COYOTE1

clearing old ssid.
writing eeprom ssid.
COYOTE1
Sending webHandleTimeZoneSetup
clearing old pass.
MYPASSWORDHERE

writing eeprom pass.
MYPASSWORDHERE
Sending webHandleTimeZoneSetup
clearing old pass.
MYPASSWORDHERE

writing eeprom pass.
MYPASSWORDHERE
Sending webHandleTimeZoneSetup
clearing old pass.
MYPASSWORDHERE

writing eeprom pass.
MYPASSWORDHERE
Sending webHandleTimeZoneSetup
clearing old pass.
MYPASSWORDHERE

writing eeprom pass.
MYPASSWORDHERE

////////   NOTHING HAPPENS THEN - WEBPAGE BLANK - NO TIMEZONE SETTINGS - HAVE TO REBOOT NODEMCU ////

SSID: COYOTE1
PASS: MYPASSWORDHERE
latitude: 0.00
longitude: 0:00
timezonevalue: 10
timezone: -6.00
randommode: 0
hourmarks: 0
sleep: 22
sleepmin: 0
showseconds: 1
DSTauto: 0
webMode: 1
wake: 7
wakemin: 0
brightness: 100
DST (true/false): 0

Startup
Connecting to Wifi COYOTE1
Waiting for Wifi to connect
..............
Wifi connected
mDNS responder started
Starting SSDP...
192.168.2.54
Web server started
Receive NTP Response
nightmode 1
SSDP packet sent
Sending handleRoot

////////  I can now access http://thelightclock.local - Cannot reach settings when clicking SETTINGS BUTTON !!!/////

Sending handleSettings
22:00
07:00
Sending handleSettings
22:00
07:00

///////// WHEN CHANGING BRIGHTNESS AND CLICKING UPDATE THE LIGHT CLOCK /////

40
Sending handleRoot

///////// WHEN CLICKING

**Comment by simpleex** [comment]
OK,

I can reach /timezone /switchwebmode /timeset route but no luck with /settings

**Comment by chrismelba** [comment]
I've just synced up the latest version. Maybe try re-install that? I
haven't actually looked at the code in a week or so as I'm focussed on the
manufacture for the Kickstarter right now.

**Comment by lovelesh** [comment]
There are some issues with EEPROM: even if you erase your EEPROM, nodemcu v1.0 remembers the SSID and password
Also I am having some issues with broadcasting and muticasting: the UDP packet is of desired content on first flash but when I reboot the packet length decreases. I am using the same commands for UDP as you did in your code. 

Is there any work around?

**Comment by chrismelba** [comment]
Hmmm I may have synced some slightly bad code up to github. I'm not very
good at keeping my local git in sync. Let me reload tomorrow and you can
try again?

**Comment by numer** [comment]
Any news on this issue, I'm facing the same problem where the esp-12e crashes anytime when the ssid is chosen and submit.

**Comment by chrismelba** [comment]
Just uploaded the final build, maybe give it a try?

**Comment by Sibilia** [comment]
Hi. I had the same problem. Crash occurred when PROGMEM type variables used as string.
`String toSend = password_html;` (for example)
to fix this you need to use FPSTR() for PROGMEM:
`String toSend = FPSTR(password_html);`

doc: http://esp8266.github.io/Arduino/versions/2.1.0-rc2/doc/reference.html#progmem

I fixed it in the first commit in pull request #5

**Comment by numer** [comment]
I can confirm that adding Sibilia's changes resolves the problem!

**Comment by chrismelba** [comment]
Thanks guys! I'll pull it into master after Easter!
