### ISSUE TITLE
ssid & password are double

### ISSUE THREAD

**Issue by wunderbaum** [chrismelba/lightclockwifiv2#4]
I tried to compile my own version because I have a 60-LED stripe and not one with 144 pixels.
Unfortunately, this does not work as it does not store the ssid and password correct. In serial console, I see it double and that makes trouble.
I tried to hardcode the ssid and pass in the code, but it always reloads the eeprom information.

**Comment by chrismelba** [comment]
Try a couple of times to program ssid and password. I'm having some
troubles with it at the moment I don't understand but it seems to work on
second or third try
